apiVersion: apps/v1
kind: Deployment
metadata:
  name: sava-product-1.0.3
  namespace: sava
  labels:
    app: sava-product
spec:
  selector:
    matchLabels:
      app: sava-product
  replicas: 1
  template:
    metadata:
      labels:
        app: sava-product
        version: 1.0.3
    spec:
      containers:
      - name: sava-product
        image: vampio/sava-product:1.0.3
        ports:
        - containerPort: 8080
